schema_version: 1

context:
  version: "1.2.1"

package:
  name: helm-unittest
  version: ${{ version }}

source:
  url: https://github.com/helm-unittest/helm-unittest/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3911ab4535c5c8d58c36b555ae3cb7f457cca32eda9fa23424b4f764f6604662

build:
  number: 0
  script:
    - go-licenses save ./cmd/helm-unittest --save_path ./library_licenses
    - if: unix
      then: go build -v -o $PREFIX/bin/helm-unittest -ldflags="-X github.com/helm-unittest/helm-unittest/internal/build.version=${{ version }}" ./cmd/helm-unittest
      else: go build -v -o %LIBRARY_BIN%\helm-unittest.exe -ldflags="-X github.com/helm-unittest/helm-unittest/internal/build.version=${{ version }}" ./cmd/helm-unittest
requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: helm-unittest --help
  - package_contents:
      bin:
        - helm-unittest
      strict: true

about:
  homepage: https://github.com/helm-unittest/helm-unittest
  summary: Unit test for helm chart in YAML to keep your chart consistent and robust!
  description: BDD styled unit test framework for Kubernetes Helm charts as a Helm plugin.
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/
  documentation: https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md
  repository: https://github.com/helm-unittest/helm-unittest

extra:
  recipe-maintainers:
    - aaronlionsheep
